version: '3.8'
services:
  db:
    image: mongo:8.0.3
    container_name: mongo_dayanneduque
    restart: always
    volumes:
      - /root/system/vols/dayanneduque/mongo/config:/etc/mongo
      - /root/system/vols/dayanneduque/mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  backend:
    build: ./Backend
    container_name: backend_dayanneduque
    ports:
      - "5890:3000"
    environment:
      - MONGO_URI=mongodb://root:root@db:27017/habilident?authSource=admin
      - SECRET_KEY=habilident
      - ORIGIN_HOST=https://dayanneduque.ig-soft.com
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=dra.dayanneduque@gmail.com
      - EMAIL_PASSWORD=nzxxuitjfqoxrwoi
      - NODE_ENV=production
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 'ALL'
  frontend:
    build:
      context: ./Frontend
      args:
        - BACKEND_URL=https://dayanneduque.ig-soft.com/api
        - BACKEND_SOCKET=https://dayanneduque.ig-soft.com
    container_name: frontend_dayanneduque
    ports:
      - "5891:8080"
